### ISSUE TITLE
Questions about the mask scheduling function

### ISSUE THREAD

**Issue by stein-666** [valeoai/Maskgit-pytorch#17]
Hi, thanks for your great open-source work! I have two questions about the mask scheduler initialization when running the inference.

In your code, the mask scheduling function is set to arccos: `val_to_mask = torch.arccos(r) / (math.pi * 0.5)`. However, in the original MaskGIT paper, it is set to the cos function. I’m not sure about the purpose of this difference in the code.
When you initialize the input of the mask scheduling function, you choose `r = torch.linspace(1, 0, step)`. But the paper claims that the input of the function should be _0/T, 1/T…(T-1)/T_, which is different from `torch.linspace(1, 0, step)=0/(step-1), 1/(step-1)...1`. I’m not sure if I have misunderstood the paper.

**Comment by llvictorll** [comment]
Hello, thank for the question,

The arccos scheduler masks, on average, a larger portion of the image. Please see the [technical report](https://arxiv.org/abs/2310.14400).

The line `r = torch.linspace(1, 0, step)` is slightly different, but I think it is a minor detail. Having `T = step + 1` should result in the same scheduler.

Best regards,

Victor

**Comment by stein-666** [comment]
Thank you for your reply.  My question has been resolved.
