### ISSUE TITLE
Warm-up of CFG weight

### ISSUE THREAD

**Issue by yukara-ikemiya** [valeoai/Maskgit-pytorch#2]
First of all, thank you for providing such great codes and materials. I was also struggling to reproduce MaskGIT, so it has been a tremendous help.

I noticed an implementation that was not mentioned in the report, which is the warm-up of CFG weight during sampling.
https://github.com/valeoai/Maskgit-pytorch/blob/3e5d3ebe84585e075554b694007bf5d66dee06f0/Trainer/vit.py#L372
If you don't mind, could you please provide insights into the differences in results when this warm-up is applied versus not applied?

Here's another minor point, but would it be more in line with the intended processing if the weight calculation is modified as follows?
`_w = w * (indice / (len(scheduler)-1))`

**Comment by llvictorll** [comment]
Hello, 

You are right, I forgot to mention this in the report. Actually, the warm-up on the CFG comes from the [MUSE paper](https://arxiv.org/abs/2301.00704)(Section 2.7): "This allows the early tokens to be sampled more freely.
with little or no guidance, but increases the influence of the conditioning prompt on the later tokens".

I'll try to do some experiments on the influence of this warm-up when I have time, and update the report accordingly. But I cannot give you an exact release date.

Thanks for the correction of the weight calculation, I will also update the code :) 

Best, 

Victor

**Comment by yukara-ikemiya** [comment]
Thank you for the reply! I've also read the MUSE paper, but I might miss that part. I'll check it out!
I'll also investigate how each technique affects sampling results by myself.
Let me close this thread.

Best regard,
Yukara
