### ISSUE TITLE
Unneccesary Dropout layer in FeedForward network

### ISSUE THREAD

**Issue by yukara-ikemiya** [valeoai/Maskgit-pytorch#4]
According to the original implementation, may the following Dropout layer not be needed?
(even though Dropout is applied in this position in the original BERT implementation)
https://github.com/valeoai/Maskgit-pytorch/blob/d2ba643ccd915d81895089e87d287445a16416a1/Network/transformer.py#L41

(original): https://github.com/google-research/maskgit/blob/main/maskgit/nets/maskgit_transformer.py#L78

**Comment by llvictorll** [comment]
Hi, I haven't tried it without the intermediate dropout. But I think this is a small difference that should not drastically affect the performance. :)

**Comment by yukara-ikemiya** [comment]
Thank you for the reply! I also feel every implementation has minor change, and there seems to be large difference in terms of final performance.

thanks!
