### ISSUE TITLE
How can I use my own dataset to train maskgit?

### ISSUE THREAD

**Issue by zxb-0** [valeoai/Maskgit-pytorch#8]
@llvictorll How can I use my own dataset to train maskgit?

**Comment by llvictorll** [comment]
Hello, 
All you have to do is provide your own Pytorch dataset and update the method "get_data" [here](https://github.com/valeoai/Maskgit-pytorch/blob/b0b2b3cc11cffd0b159f22dc1c6e73a7e8b53db3/Trainer/trainer.py#L41)

Victor

**Comment by zxb-0** [comment]
@llvictorll thank you very much
